export const CHANGE_EXPRESSION_FIELD = 'CHANGE_EXPRESSION_FIELD';
export const CHARGE_VARIABLES = 'CHARGE_VARIABLES';
export const VARIABLE_MODIFIED = 'VARIABLE_MODIFIED';
export const CALCULATE_RESULT = 'CALCULATE_RESULT';