export const CHANGE_EXPRESSION_FIELD = 'CHANGE_EXPRESSION_FIELD';
export const ADD_VARIABLE = 'ADD_VARIABLE';
export const REMOVE_VARIABLE = 'REMOVE_VARIABLE';
export const CALCULATE_RESULT = 'CALCULATE_RESULT';