export const CHANGE_EXPRESSION_FIELD = 'CHANGE_EXPRESSION_FIELD';
export const ADD_VARIABLE = 'ADD_VARIABLE';
export const REMOVE_VARIABLE = 'REMOVE_VARIABLE';
export const CHARGE_VARIABLES = 'CHARGE_VARIABLES';
export const MODIFY_VARIABLE_FIELD = 'MODIFY_VARIABLE_FIELD'
export const CALCULATE_RESULT = 'CALCULATE_RESULT';