export const EXPRESSION_FIELD_CHANGED = 'EXPRESSION_FIELD_CHANGED';
export const VARIABLES_CHARGED = 'VARIABLES_CHARGED';
export const VARIABLE_MODIFIED = 'VARIABLE_MODIFIED';
export const RESULT_CALCULATED = 'RESULT_CALCULATED';